# Generated by Django 5.1.2 on 2024-11-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
