# Generated by Django 3.0 on 2024-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20241119_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.CharField(max_length=10),
        ),
    ]
